### ISSUE TITLE
How to get repeated results?

### ISSUE THREAD

**Issue by QLgogo** [xuyiqing/fect#11]
Hi, I got some issues in getting repeated results. For example, I run the function "fect()" (method = "mc") on my data twice, without changing any arguments inputted. However, the magnitudes of the results for these two estimations are not exactly the same. I tried to set seed but still cannot get repeated results. Would you mind telling me why this happened and how could I get repeated results? Many thanks in advance!

**Comment by lzy318** [comment]
Hi, thanks for that. We have updated the codes, allowing setting random seeds in parallel computing, could you try it again?

**Comment by QLgogo** [comment]
Thanks for your reply. I have updated the R package and set seed within the function like fect(...seed = 1234). But still I cannot get repeated results. Could you kindly tell me the related codes to use?

**Comment by lzy318** [comment]
Can you tell me which part of the estimates is different? The estimated ATT or its standard error/confidence intervals?

**Comment by QLgogo** [comment]
The estimated ATT is identical but its standard error/confidence intervals/P values are different.

**Comment by lzy318** [comment]
OK, thanks a lot. That's a little weird. Could you send your data and codes to zyliu2016@nsd.pku.edu.cn? I will look into it. Another way to get over this problem is to set the option "parallel" to FALSE.
