### ISSUE TITLE
Error in est.att[i, 1] : subscript out of bounds

### ISSUE THREAD

**Issue by teddddddy** [xuyiqing/fect#12]
Hello, thanks a lot for this excellent work. 
When I tried to run the FEct and IFEct, I kept obtaining the subscript out of bounds error. I am not sure what's the reason and how to fix it. I wonder if this is possible due to the unbalanced dataset? Since the treatment itself takes different times and directly imputes the DV, I have to drop observations within the treatment period, and this leads to an unbalanced dataset.
Any help or information would be appreciated.

**Comment by lzy318** [comment]
Can you send a sample dataset that reports the error to zyliu2016@nsd.pku.edu.cn? I will help to debug it, thanks!
